apiVersion: v1
kind: Service
metadata:
  name: "api-server-svc"
  labels:
{{ include "remind.labels" . | indent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080 # for inner access
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "remind.api_server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
