apiVersion: v1
kind: Service
metadata:
  name: "reminder-server-svc"
  labels:
{{ include "remind.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080 # for inner access
      targetPort: 8080
      nodePort: 30080
  selector:
    app.kubernetes.io/name: {{ include "remind.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
