apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "remind.statefull_server.name" . }}
  labels:
{{ include "remind.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "remind.statefull_server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "remind.statefull_server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: "reminder-statefull"
          image: "keisunagawa/reminder-statefull:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 50051
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /list
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /list
          #     port: http
